name: CI -Vérification html
on:
  push:
    branch: {"main"}
  pull-request:
        branch: {"main"}
jobs:
  test-html:
    runs-on: ubuntu-latest
    steps: 
        - name: Récupération du code
          uses: actions/checkout@v3
        - name: Vérification du html
          uses: Cyb3r-Jak3/html5validator-action@v7.2.0
          with:
             root: .
